# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1038, 661)
        MainWindow.setStyleSheet('background-image:url(img/1.jpg)')
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setMinimumSize(QtCore.QSize(1038, 0))
        self.widget.setObjectName("widget")
        self.labelCapture = QtWidgets.QLabel(self.widget)
        self.labelCapture.setGeometry(QtCore.QRect(160, 10, 431, 271))
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(28)
        self.labelCapture.setFont(font)
        self.labelCapture.setObjectName("labelCapture")
        self.labelCamera = QtWidgets.QLabel(self.widget)
        self.labelCamera.setGeometry(QtCore.QRect(160, 340, 431, 281))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.labelCamera.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(28)
        self.labelCamera.setFont(font)
        self.labelCamera.setObjectName("labelCamera")
        self.labelResult = QtWidgets.QLabel(self.widget)
        self.labelResult.setGeometry(QtCore.QRect(700, 20, 261, 361))
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(28)
        self.labelResult.setFont(font)
        self.labelResult.setObjectName("labelResult")
        self.btnReadImage = QtWidgets.QPushButton(self.widget)
        self.btnReadImage.setGeometry(QtCore.QRect(30, 170, 81, 51))
        self.btnReadImage.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui资源库/picture_128px_1229366_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReadImage.setIcon(icon)
        self.btnReadImage.setIconSize(QtCore.QSize(40, 40))
        self.btnReadImage.setFlat(True)
        self.btnReadImage.setObjectName("btnReadImage")
        self.btnCapture = QtWidgets.QPushButton(self.widget)
        self.btnCapture.setGeometry(QtCore.QRect(30, 310, 81, 51))
        self.btnCapture.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui资源库/screenshot_128px_1223095_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCapture.setIcon(icon1)
        self.btnCapture.setIconSize(QtCore.QSize(40, 40))
        self.btnCapture.setFlat(True)
        self.btnCapture.setObjectName("btnCapture")
        self.btnOpenCamera = QtWidgets.QPushButton(self.widget)
        self.btnOpenCamera.setGeometry(QtCore.QRect(30, 30, 81, 51))
        self.btnOpenCamera.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui资源库/photo_camera_128px_1230607_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpenCamera.setIcon(icon2)
        self.btnOpenCamera.setIconSize(QtCore.QSize(40, 40))
        self.btnOpenCamera.setCheckable(False)
        self.btnOpenCamera.setAutoRepeat(False)
        self.btnOpenCamera.setAutoRepeatDelay(300)
        self.btnOpenCamera.setAutoRepeatInterval(100)
        self.btnOpenCamera.setFlat(True)
        self.btnOpenCamera.setObjectName("btnOpenCamera")
        self.btnGray = QtWidgets.QPushButton(self.widget)
        self.btnGray.setGeometry(QtCore.QRect(30, 450, 81, 51))
        self.btnGray.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui资源库/folder_arrow_128px_1222876_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGray.setIcon(icon3)
        self.btnGray.setIconSize(QtCore.QSize(40, 40))
        self.btnGray.setCheckable(False)
        self.btnGray.setFlat(True)
        self.btnGray.setObjectName("btnGray")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 80, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 220, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(40, 360, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(40, 500, 72, 15))
        self.label_4.setObjectName("label_4")
        self.information_name = QtWidgets.QLabel(self.widget)
        self.information_name.setGeometry(QtCore.QRect(700, 490, 161, 61))
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(28)
        self.information_name.setFont(font)
        self.information_name.setObjectName("information_name")
        self.information_num = QtWidgets.QLabel(self.widget)
        self.information_num.setGeometry(QtCore.QRect(700, 410, 311, 61))
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(28)
        self.information_num.setFont(font)
        self.information_num.setObjectName("information_num")
        MainWindow.setCentralWidget(self.widget)

        self.retranslateUi(MainWindow)
        self.btnOpenCamera.clicked.connect(MainWindow.btnOpenCamera_Clicked)
        self.btnReadImage.clicked.connect(MainWindow.btnReadImage_Clicked)
        self.btnCapture.clicked.connect(MainWindow.btnCapture_Clicked)
        self.btnGray.clicked.connect(MainWindow.btnGray_Clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelCapture.setText(_translate("MainWindow", "捕获图"))
        self.labelCamera.setText(_translate("MainWindow", "摄像头"))
        self.labelResult.setText(_translate("MainWindow", "结果图"))
        self.label.setText(_translate("MainWindow", "打开摄像头"))
        self.label_2.setText(_translate("MainWindow", "打开图片"))
        self.label_3.setText(_translate("MainWindow", "截取图片"))
        self.label_4.setText(_translate("MainWindow", "信息显示"))
        self.information_name.setText(_translate("MainWindow", "名字"))
        self.information_num.setText(_translate("MainWindow", "号码"))
